spring:
  application:
    name: mesa-ayuda

  datasource:
    url: jdbc:postgresql://localhost:5432/mesa_ayuda
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiracion-minutos: 15
    refresh-token-expiracion-dias: 7

server:
  port: 8080
