-- Esquema completo del dominio. Solo Ticket, Contacto, Llamada, Area, Usuario,
-- Categoria y HistorialEstado tienen entidad JPA en Sprint 1; el resto de las
-- tablas existen desde ya para que las migraciones futuras solo agreguen
-- columnas o datos, nunca la estructura base.

-- =========================================================================
-- area
-- =========================================================================
create table area (
    id                  bigint generated by default as identity primary key,
    nombre              varchar(100)  not null,
    recibe_llamadas     boolean       not null default false,
    limite_wip_agente   integer       not null default 5,
    activo              boolean       not null default true,
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0,
    constraint uq_area_nombre unique (nombre),
    constraint chk_area_limite_wip check (limite_wip_agente > 0)
);

-- =========================================================================
-- usuario
-- =========================================================================
create table usuario (
    id                  bigint generated by default as identity primary key,
    nombre_completo     varchar(150)  not null,
    correo              varchar(150)  not null,
    rol                 varchar(20)   not null,
    area_id             bigint        not null references area(id),
    activo              boolean       not null default true,
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0,
    constraint uq_usuario_correo unique (correo),
    constraint chk_usuario_rol check (rol in ('AGENTE', 'SUPERVISOR', 'ADMIN'))
);

create index idx_usuario_area_id on usuario (area_id);
create index idx_usuario_rol on usuario (rol);

-- =========================================================================
-- contacto (cliente, sin credenciales)
-- =========================================================================
create table contacto (
    id                  bigint generated by default as identity primary key,
    nombre_completo     varchar(150)  not null,
    telefono            varchar(30)   not null,
    correo              varchar(150),
    activo              boolean       not null default true,
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0
);

create index idx_contacto_telefono on contacto (telefono);

-- =========================================================================
-- categoria
-- =========================================================================
create table categoria (
    id                  bigint generated by default as identity primary key,
    nombre              varchar(100)  not null,
    descripcion         varchar(255),
    activo              boolean       not null default true,
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0,
    constraint uq_categoria_nombre unique (nombre)
);

-- =========================================================================
-- etiqueta
-- =========================================================================
create table etiqueta (
    id                  bigint generated by default as identity primary key,
    nombre              varchar(50)   not null,
    activo              boolean       not null default true,
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0,
    constraint uq_etiqueta_nombre unique (nombre)
);

-- =========================================================================
-- calendario_laboral
-- =========================================================================
create table calendario_laboral (
    id                  bigint generated by default as identity primary key,
    nombre              varchar(100)  not null,
    zona_horaria        varchar(50)   not null,
    hora_inicio         time          not null,
    hora_fin            time          not null,
    aplica_lunes        boolean       not null default true,
    aplica_martes       boolean       not null default true,
    aplica_miercoles    boolean       not null default true,
    aplica_jueves       boolean       not null default true,
    aplica_viernes      boolean       not null default true,
    aplica_sabado       boolean       not null default false,
    aplica_domingo      boolean       not null default false,
    activo              boolean       not null default true,
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0,
    constraint uq_calendario_laboral_nombre unique (nombre)
);

-- =========================================================================
-- politica_sla
-- =========================================================================
create table politica_sla (
    id                          bigint generated by default as identity primary key,
    nombre                      varchar(100)  not null,
    prioridad                   varchar(10)   not null,
    minutos_resolucion          integer       not null,
    minutos_primera_respuesta   integer,
    activo                      boolean       not null default true,
    creado_en                   timestamptz   not null default now(),
    actualizado_en              timestamptz   not null default now(),
    creado_por                  varchar(100)  not null,
    actualizado_por             varchar(100)  not null,
    version                     bigint        not null default 0,
    constraint uq_politica_sla_nombre unique (nombre),
    constraint chk_politica_sla_prioridad check (prioridad in ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    constraint chk_politica_sla_minutos_resolucion check (minutos_resolucion > 0),
    constraint chk_politica_sla_minutos_primera_respuesta check (minutos_primera_respuesta is null or minutos_primera_respuesta > 0)
);

-- una sola política activa por nivel de prioridad
create unique index uq_politica_sla_prioridad_activa on politica_sla (prioridad) where activo;

-- =========================================================================
-- llamada
-- =========================================================================
create table llamada (
    id                     bigint generated by default as identity primary key,
    contacto_id            bigint        not null references contacto(id),
    usuario_atiende_id     bigint        not null references usuario(id),
    fecha_hora             timestamptz   not null default now(),
    duracion_segundos      integer,
    creado_en              timestamptz   not null default now(),
    actualizado_en         timestamptz   not null default now(),
    creado_por             varchar(100)  not null,
    actualizado_por        varchar(100)  not null,
    version                bigint        not null default 0,
    constraint chk_llamada_duracion check (duracion_segundos is null or duracion_segundos >= 0)
);

create index idx_llamada_contacto_id on llamada (contacto_id);
create index idx_llamada_usuario_atiende_id on llamada (usuario_atiende_id);
create index idx_llamada_fecha_hora on llamada (fecha_hora);

-- =========================================================================
-- ticket
-- =========================================================================
create table ticket (
    id                     bigint generated by default as identity primary key,
    codigo                 varchar(20)   not null,
    llamada_id             bigint        references llamada(id),
    contacto_id            bigint        not null references contacto(id),
    area_actual_id         bigint        not null references area(id),
    categoria_id           bigint        not null references categoria(id),
    usuario_creador_id     bigint        not null references usuario(id),
    tipo                   varchar(20)   not null,
    estado                 varchar(25)   not null,
    prioridad              varchar(10)   not null,
    urgencia                varchar(10)   not null,
    impacto                varchar(15)   not null,
    origen                 varchar(10)   not null default 'TELEFONO',
    titulo                 varchar(200)  not null,
    descripcion             text          not null,
    resuelto_en_llamada    boolean       not null default false,
    solucion               text,
    minutos_pausado        integer       not null default 0,
    eliminado_en           timestamptz,
    creado_en              timestamptz   not null default now(),
    actualizado_en         timestamptz   not null default now(),
    creado_por             varchar(100)  not null,
    actualizado_por        varchar(100)  not null,
    version                bigint        not null default 0,
    constraint uq_ticket_codigo unique (codigo),
    constraint chk_ticket_tipo check (tipo in ('INCIDENTE', 'SOLICITUD')),
    constraint chk_ticket_estado check (estado in ('NUEVO', 'DERIVADO', 'EN_PROGRESO', 'ESPERANDO_CLIENTE', 'RESUELTO', 'CERRADO')),
    constraint chk_ticket_prioridad check (prioridad in ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
    constraint chk_ticket_urgencia check (urgencia in ('BAJA', 'MEDIA', 'ALTA')),
    constraint chk_ticket_impacto check (impacto in ('INDIVIDUAL', 'AREA', 'ORGANIZACION')),
    constraint chk_ticket_origen check (origen in ('TELEFONO', 'CORREO', 'WEB', 'CHAT')),
    constraint chk_ticket_minutos_pausado check (minutos_pausado >= 0),
    constraint chk_ticket_origen_telefono check (origen <> 'TELEFONO' or llamada_id is not null)
);

create index idx_ticket_estado on ticket (estado);
create index idx_ticket_area_actual_id on ticket (area_actual_id);
create index idx_ticket_prioridad on ticket (prioridad);
create index idx_ticket_contacto_id on ticket (contacto_id);
create index idx_ticket_categoria_id on ticket (categoria_id);
create index idx_ticket_llamada_id on ticket (llamada_id);
create index idx_ticket_area_estado on ticket (area_actual_id, estado);

-- =========================================================================
-- historial_estado (solo-inserción: nunca update ni delete)
-- =========================================================================
create table historial_estado (
    id                  bigint generated by default as identity primary key,
    ticket_id           bigint        not null references ticket(id),
    estado_anterior     varchar(25),
    estado_nuevo        varchar(25)   not null,
    usuario_id          bigint        not null references usuario(id),
    comentario          varchar(500),
    creado_en           timestamptz   not null default now(),
    creado_por          varchar(100)  not null
);

create index idx_historial_estado_ticket_id on historial_estado (ticket_id);
create index idx_historial_estado_creado_en on historial_estado (creado_en);

-- =========================================================================
-- derivacion (solo-inserción: nunca update ni delete)
-- =========================================================================
create table derivacion (
    id                  bigint generated by default as identity primary key,
    ticket_id           bigint        not null references ticket(id),
    area_origen_id      bigint        not null references area(id),
    area_destino_id     bigint        not null references area(id),
    usuario_deriva_id   bigint        not null references usuario(id),
    motivo              varchar(500)  not null,
    creado_en           timestamptz   not null default now(),
    creado_por          varchar(100)  not null
);

create index idx_derivacion_ticket_id on derivacion (ticket_id);
create index idx_derivacion_area_destino_id on derivacion (area_destino_id);

-- =========================================================================
-- comentario
-- =========================================================================
create table comentario (
    id                  bigint generated by default as identity primary key,
    ticket_id           bigint        not null references ticket(id),
    usuario_id          bigint        not null references usuario(id),
    visibilidad         varchar(10)   not null,
    contenido           text          not null,
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0,
    constraint chk_comentario_visibilidad check (visibilidad in ('PUBLICO', 'INTERNO'))
);

create index idx_comentario_ticket_id on comentario (ticket_id);
create index idx_comentario_visibilidad on comentario (visibilidad);

-- =========================================================================
-- adjunto
-- =========================================================================
create table adjunto (
    id                      bigint generated by default as identity primary key,
    ticket_id               bigint        not null references ticket(id),
    comentario_id           bigint        references comentario(id),
    usuario_id              bigint        not null references usuario(id),
    nombre_archivo          varchar(255)  not null,
    tipo_mime               varchar(100)  not null,
    tamano_bytes            bigint        not null,
    ruta_almacenamiento     varchar(500)  not null,
    activo                  boolean       not null default true,
    creado_en               timestamptz   not null default now(),
    actualizado_en          timestamptz   not null default now(),
    creado_por              varchar(100)  not null,
    actualizado_por         varchar(100)  not null,
    version                 bigint        not null default 0,
    constraint chk_adjunto_tamano check (tamano_bytes > 0)
);

create index idx_adjunto_ticket_id on adjunto (ticket_id);

-- =========================================================================
-- registro_tiempo
-- =========================================================================
create table registro_tiempo (
    id                  bigint generated by default as identity primary key,
    ticket_id           bigint        not null references ticket(id),
    usuario_id          bigint        not null references usuario(id),
    minutos             integer       not null,
    descripcion         varchar(300),
    registrado_en       timestamptz   not null default now(),
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0,
    constraint chk_registro_tiempo_minutos check (minutos > 0)
);

create index idx_registro_tiempo_ticket_id on registro_tiempo (ticket_id);

-- =========================================================================
-- feriado
-- =========================================================================
create table feriado (
    id                          bigint generated by default as identity primary key,
    calendario_laboral_id       bigint        not null references calendario_laboral(id),
    fecha                       date          not null,
    descripcion                 varchar(150)  not null,
    creado_en                   timestamptz   not null default now(),
    actualizado_en              timestamptz   not null default now(),
    creado_por                  varchar(100)  not null,
    actualizado_por             varchar(100)  not null,
    version                     bigint        not null default 0,
    constraint uq_feriado_calendario_fecha unique (calendario_laboral_id, fecha)
);

create index idx_feriado_fecha on feriado (fecha);

-- =========================================================================
-- columna_tablero
-- =========================================================================
create table columna_tablero (
    id                  bigint generated by default as identity primary key,
    area_id             bigint        not null references area(id),
    nombre              varchar(50)   not null,
    estado_asociado     varchar(25)   not null,
    orden               integer       not null,
    activo              boolean       not null default true,
    creado_en           timestamptz   not null default now(),
    actualizado_en      timestamptz   not null default now(),
    creado_por          varchar(100)  not null,
    actualizado_por     varchar(100)  not null,
    version             bigint        not null default 0,
    constraint uq_columna_tablero_area_estado unique (area_id, estado_asociado),
    constraint uq_columna_tablero_area_orden unique (area_id, orden),
    constraint chk_columna_tablero_orden check (orden >= 0),
    constraint chk_columna_tablero_estado check (estado_asociado in ('NUEVO', 'DERIVADO', 'EN_PROGRESO', 'ESPERANDO_CLIENTE', 'RESUELTO', 'CERRADO'))
);

-- =========================================================================
-- ticket_etiqueta (unión N:M)
-- =========================================================================
create table ticket_etiqueta (
    ticket_id       bigint        not null references ticket(id),
    etiqueta_id     bigint        not null references etiqueta(id),
    creado_en       timestamptz   not null default now(),
    primary key (ticket_id, etiqueta_id)
);
